/** MAV_CMD subset — common.xml */
export const MAV_CMD = {
  COMPONENT_ARM_DISARM: 400,
  NAV_TAKEOFF: 22,
  NAV_LAND: 21,
  NAV_RETURN_TO_LAUNCH: 20,
  DO_PAUSE_CONTINUE: 193,
  DO_SET_MODE: 176,
  REQUEST_AUTOPILOT_CAPABILITIES: 520,
  REQUEST_PROTOCOL_VERSION: 519,
  GET_HOME_POSITION: 410,
  SET_MESSAGE_INTERVAL: 511,
} as const;

/** MAV_RESULT — ack.result field */
export const MAV_RESULT = {
  ACCEPTED: 0,
  TEMPORARILY_REJECTED: 1,
  DENIED: 2,
  UNSUPPORTED: 3,
  FAILED: 4,
  IN_PROGRESS: 5,
} as const;
